### ISSUE TITLE
PG::UndefinedFunction: ERROR:  function ll_to_earth(character varying, character varying) does not exist

### ISSUE THREAD

**Issue by fenec** [diogob/activerecord-postgres-earthdistance#22]
I receive `PG::UndefinedFunction: ERROR:  function ll_to_earth(character varying, character varying) does not exist` when running following:
`Model.within_radius(100, -22.951916, -43.210487)` even though I've set up the extensions and can see them installed for the database:

 cube          | 1.0     | public     | data type for multidimensional cubes
 earthdistance | 1.0     | public     | calculate great-circle distances on the surface of the Earth
 plpgsql       | 1.0     | pg_catalog | PL/pgSQL procedural language
 
I understand it's PG issue but probably someone has the same problem here?
I am on Mac with `Postgres.app`

**Comment by diogob** [comment]
@fenec if you clone the repo, are you able to run the test suite?
Try
```
bundle
bundle exec rspec
```
In repo directory after cloning. Could you do this and report back the test results?

**Comment by fenec** [comment]
@diogob 
thanks for reponse!
16 examples, 0 failures

**Comment by fenec** [comment]
Got it - I had `lat` and `lng` columns as `string` (varchar) instead of float.
